"""Tests for SQLAlchemyTransactionRepository."""

import pytest
from datetime import datetime, timedelta
from decimal import Decimal
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

from src.infrastructure.database.config import Base
from src.infrastructure.database.transaction_repository_impl import SQLAlchemyTransactionRepository
from src.domain.entities.transaction import Transaction


@pytest.fixture
def db_session():
    """Create in-memory SQLite database for testing."""
    engine = create_engine("sqlite:///:memory:")
    Base.metadata.create_all(engine)
    SessionLocal = sessionmaker(bind=engine)
    session = SessionLocal()
    
    yield session
    
    session.close()


@pytest.fixture
def transaction_repository(db_session):
    """Create TransactionRepository instance."""
    return SQLAlchemyTransactionRepository(db_session)


@pytest.mark.asyncio
async def test_save_new_transaction(transaction_repository):
    """Test saving a new transaction."""
    transaction = Transaction(
        user_id=123456,
        amount=Decimal("100.50"),
        category="Thu nhập",
        note="Test income"
    )
    
    saved = await transaction_repository.save(transaction)
    
    assert saved.user_id == 123456
    assert saved.amount == Decimal("100.50")
    assert saved.category == "Thu nhập"
    # transaction_id is UUID generated by entity
    assert len(saved.transaction_id) > 0


@pytest.mark.asyncio
async def test_get_by_id(transaction_repository):
    """Test getting transaction by ID."""
    transaction = Transaction(
        user_id=123456,
        amount=Decimal("50.00"),
        category="Chi tiêu"
    )
    saved = await transaction_repository.save(transaction)
    
    retrieved = await transaction_repository.get_by_id(saved.transaction_id)
    
    assert retrieved is not None
    assert retrieved.transaction_id == saved.transaction_id
    assert retrieved.amount == Decimal("50.00")


@pytest.mark.asyncio
async def test_delete_transaction(transaction_repository):
    """Test deleting transaction."""
    transaction = Transaction(user_id=123456, amount=Decimal("100"), category="Test")
    saved = await transaction_repository.save(transaction)
    
    deleted = await transaction_repository.delete(saved.transaction_id)
    assert deleted is True
    
    retrieved = await transaction_repository.get_by_id(saved.transaction_id)
    assert retrieved is None


@pytest.mark.asyncio
async def test_get_recent(transaction_repository):
    """Test getting recent transactions."""
    now = datetime.utcnow()
    for i in range(15):
        transaction = Transaction(
            user_id=123456,
            amount=Decimal(str((i + 1) * 10)),  # Avoid zero amount
            category="Test",
            date=now - timedelta(days=i)
        )
        await transaction_repository.save(transaction)
    
    recent = await transaction_repository.get_recent(123456, limit=5)
    
    assert len(recent) == 5
    # Should be ordered by date descending (most recent first)
    # recent[0] has date=now, recent[1] has date=now-1day
    assert recent[0].date >= recent[1].date


@pytest.mark.asyncio
async def test_get_by_date_range(transaction_repository):
    """Test getting transactions by date range."""
    now = datetime.utcnow()
    
    # Transaction 10 days ago
    t1 = Transaction(user_id=123456, amount=Decimal("100"), category="Test", date=now - timedelta(days=10))
    # Transaction 5 days ago
    t2 = Transaction(user_id=123456, amount=Decimal("200"), category="Test", date=now - timedelta(days=5))
    # Transaction today
    t3 = Transaction(user_id=123456, amount=Decimal("300"), category="Test", date=now)
    
    await transaction_repository.save(t1)
    await transaction_repository.save(t2)
    await transaction_repository.save(t3)
    
    # Get transactions from 7 days ago to now
    start_date = now - timedelta(days=7)
    transactions = await transaction_repository.get_by_date_range(123456, start_date, now)
    
    assert len(transactions) == 2  # t2 and t3


@pytest.mark.asyncio
async def test_get_by_category(transaction_repository):
    """Test getting transactions by category."""
    t1 = Transaction(user_id=123456, amount=Decimal("100"), category="Ăn uống")
    t2 = Transaction(user_id=123456, amount=Decimal("200"), category="Di chuyển")
    t3 = Transaction(user_id=123456, amount=Decimal("150"), category="Ăn uống")
    
    await transaction_repository.save(t1)
    await transaction_repository.save(t2)
    await transaction_repository.save(t3)
    
    food_transactions = await transaction_repository.get_by_category(123456, "Ăn uống")
    
    assert len(food_transactions) == 2
    assert all(t.category == "Ăn uống" for t in food_transactions)


@pytest.mark.asyncio
async def test_get_income_total(transaction_repository):
    """Test calculating total income."""
    t1 = Transaction(user_id=123456, amount=Decimal("1000"), category="Lương")
    t2 = Transaction(user_id=123456, amount=Decimal("-500"), category="Chi tiêu")
    t3 = Transaction(user_id=123456, amount=Decimal("300"), category="Thưởng")
    
    await transaction_repository.save(t1)
    await transaction_repository.save(t2)
    await transaction_repository.save(t3)
    
    total_income = await transaction_repository.get_income_total(123456)
    
    assert total_income == Decimal("1300")  # 1000 + 300


@pytest.mark.asyncio
async def test_get_expense_total(transaction_repository):
    """Test calculating total expenses."""
    t1 = Transaction(user_id=123456, amount=Decimal("1000"), category="Lương")
    t2 = Transaction(user_id=123456, amount=Decimal("-500"), category="Ăn uống")
    t3 = Transaction(user_id=123456, amount=Decimal("-200"), category="Di chuyển")
    
    await transaction_repository.save(t1)
    await transaction_repository.save(t2)
    await transaction_repository.save(t3)
    
    total_expense = await transaction_repository.get_expense_total(123456)
    
    assert total_expense == Decimal("700")  # 500 + 200 (absolute values)


@pytest.mark.asyncio
async def test_count_by_user(transaction_repository):
    """Test counting transactions by user."""
    for i in range(5):
        transaction = Transaction(user_id=123456, amount=Decimal(str((i + 1) * 10)), category="Test")  # Avoid zero
        await transaction_repository.save(transaction)
    
    # Add transaction for different user
    other_transaction = Transaction(user_id=999999, amount=Decimal("100"), category="Test")
    await transaction_repository.save(other_transaction)
    
    count = await transaction_repository.count_by_user(123456)
    
    assert count == 5


@pytest.mark.asyncio
async def test_get_income_total_with_date_range(transaction_repository):
    """Test calculating income with date range filter."""
    now = datetime.utcnow()
    
    t1 = Transaction(user_id=123456, amount=Decimal("1000"), category="Old", date=now - timedelta(days=40))
    t2 = Transaction(user_id=123456, amount=Decimal("500"), category="Recent", date=now - timedelta(days=10))
    t3 = Transaction(user_id=123456, amount=Decimal("300"), category="Today", date=now)
    
    await transaction_repository.save(t1)
    await transaction_repository.save(t2)
    await transaction_repository.save(t3)
    
    # Get income for last 30 days
    start_date = now - timedelta(days=30)
    total_income = await transaction_repository.get_income_total(123456, start_date=start_date)
    
    assert total_income == Decimal("800")  # 500 + 300 (excluding old transaction)
